DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE customers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(15) NOT NULL,
  is_owner BOOLEAN NOT NULL DEFAULT FALSE
)

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,

  order_datetime TIMESTAMP NOT NULL,
  is_fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
  special_instructions TEXT
)

CREATE TABLE order_meals (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  meal_id INTEGER REFERENCES meals(id) ON DELETE CASCADE,

  meal_quantity INTEGER NOT NULL DEFAULT 0
)
