DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS meals CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_meals CASCADE;

CREATE TABLE customers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(15) NOT NULL
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
  est_completion_time SMALLINT,
  order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_fulfilled BOOLEAN NOT NULL DEFAULT FALSE,
  special_instructions TEXT
);

CREATE TABLE meals (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL DEFAULT 0
);

CREATE TABLE order_meals (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  meal_id INTEGER REFERENCES meals(id) ON DELETE CASCADE,

  meal_quantity INTEGER NOT NULL
);
